### ISSUE TITLE
iam on kali

### ISSUE THREAD

**Issue by SharDX** [aperechnev/dns-amp-util#2]
which file should i open first ?
when i try ./Main 
./main.c: line 1: //: Is a directory
./main.c: line 2: //: Is a directory
./main.c: line 3: //: Is a directory
./main.c: line 4: //: Is a directory
./main.c: line 5: //: Is a directory
./main.c: line 6: syntax error near unexpected token `('
./main.c: line 6:`//  Copyright (c) 2013 Alexander Perechnev. All rights reserved.'

**Comment by aperechnev** [comment]
`main.c` is not a script or executable file. It's a source code written in `C` language. You have to compile it before executing. I can add a `Makefile` a bit later if you need it.
